name: Ranker
version: 1.0.1-SNAPSHOT
main: fun.seaksol.ranker.Main
author: Seaksol
commands:
  ranker:
    usage: /ranker <Parameter> <Player> <RankName>
  colormsg:
    usage: /colormsg <Parameter> <Player> <Color>