name: Ranker
version: 1.1.1
main: fun.seaksol.ranker.Main
author: Seaksol
commands:
  ranker:
    usage: /ranker <Parameter> <Player> <RankName>
  colormsg:
    usage: /colormsg <Parameter> <Player> <Color>